### ISSUE TITLE
Extension fails after updating stylelint and stylelint-config-recommended

### ISSUE THREAD

**Issue by langdonx** [mrmlnc/vscode-stylefmt#156]
Summary: I updated `stylelint-config-recommended` today and now I can't format my SCSS files.  Does this extension use its own local version of `stylelint` that might be outdated?  Is there a way for it to use the `stylelint` installed in the working directory's node_modules if it exists?

### Environment

  * VSCode Version: 1.26.1
  * OS Version: Windows 10

### Actual behavior

When I run the stylefmt command, this dumps in the console:

```
Error: Undefined rule font-family-no-missing-generic-family-keyword
	at module.exports (C:\Users\langdonx\.vscode\extensions\mrmlnc.vscode-stylefmt-2.5.0\node_modules\stylelint\lib\utils\configurationError.js:8:27)
	at Object.keys.forEach.ruleName (C:\Users\langdonx\.vscode\extensions\mrmlnc.vscode-stylefmt-2.5.0\node_modules\stylelint\lib\augmentConfig.js:279:13)
	at Array.forEach (<anonymous>)
	at normalizeAllRuleSettings (C:\Users\langdonx\.vscode\extensions\mrmlnc.vscode-stylefmt-2.5.0\node_modules\stylelint\lib\augmentConfig.js:275:29)
	at augmentConfigBasic.then.then.then.then.augmentedConfig (C:\Users\langdonx\.vscode\extensions\mrmlnc.vscode-stylefmt-2.5.0\node_modules\stylelint\lib\augmentConfig.js:84:12)
	at <anonymous>
```

### Expected behavior

The document should format with an error.

### Steps to reproduce

In my package.json:
```
    "stylelint": "9.5.0",
    "stylelint-config-recommended": "2.1.0",
```

**Comment by mrmlnc** [comment]
Fixed by #162.
